### ISSUE TITLE
Suggestion: Improve Performance by precomputing full table

### ISSUE THREAD

**Issue by aikar** [jotson/LootTable.js#3]
to improve the performance of choose, you should rebuild an array of the weighted choices.

This will front load all performance cost to the construction of the loot pool (ideally, once) instead of it being rebuilt every loot choice.

Then choose can be a simple return this.cachedArray[randomIndex];

**Comment by jotson** [comment]
Happy to accept a pull request.

**Comment by aikar** [comment]
Why was this closed?

**Comment by jotson** [comment]
Nothing personal, it's just that I don't think it's an issue and I know I will never do this. If you want to do it, go for it.
